# Generated by Django 5.0.6 on 2024-06-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_patient_doctor_delete_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='is_caregiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_caregiver',
            field=models.BooleanField(default=False),
        ),
    ]
