# Generated by Django 5.0.6 on 2024-06-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_caregiver_is_caregiver_patient_is_caregiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='is_caregiver',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_caregiver',
        ),
    ]
