# Generated by Django 5.0.6 on 2024-06-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('medication', 'Medication'), ('supplement', 'Supplement')], max_length=20)),
                ('product_name', models.CharField(max_length=200)),
                ('dosage_unit', models.CharField(choices=[('mg', 'mg'), ('µg', 'µg'), ('g', 'g'), ('ml', 'ml'), ('l', 'l'), ('IU', 'IU')], max_length=50)),
                ('dosage_type', models.CharField(choices=[('pill', 'Pill'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('capsule', 'Capsule'), ('tablet', 'Tablet'), ('ointment', 'Ointment'), ('powder', 'Powder')], max_length=50)),
                ('dosage_amount', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
