# Generated by Django 5.0.6 on 2024-06-13 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IntakeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ManyToManyField(related_name='weekdays', to='medications.day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='times',
            field=models.ManyToManyField(related_name='dose_times', to='medications.intaketime'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], max_length=10)),
                ('type', models.CharField(default='reminder', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.day')),
                ('intake_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.intakeschedule')),
                ('scheduled_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.intaketime')),
            ],
        ),
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medications.notification')),
            ],
        ),
        migrations.CreateModel(
            name='UserPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('medication', 'Medication'), ('supplement', 'Supplement')], max_length=20)),
                ('product_name', models.CharField(max_length=200)),
                ('dosage_unit', models.CharField(choices=[('mg', 'mg'), ('µg', 'µg'), ('g', 'g'), ('ml', 'ml'), ('l', 'l'), ('IU', 'IU')], max_length=50)),
                ('dosage_type', models.CharField(choices=[('pill', 'Pill'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('capsule', 'Capsule'), ('tablet', 'Tablet'), ('ointment', 'Ointment'), ('powder', 'Powder')], max_length=50)),
                ('dosage_amount', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='static/images/')),
                ('start_date', models.DateField()),
                ('is_on_going', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('presc_valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='intaketime',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.userprescription'),
        ),
        migrations.AddField(
            model_name='intakeschedule',
            name='userprescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.userprescription'),
        ),
        migrations.AddField(
            model_name='day',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.userprescription'),
        ),
    ]
