# Generated by Django 5.0.6 on 2024-06-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IntakeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.CharField(max_length=50)),
                ('user_intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.userprescription')),
                ('times', models.ManyToManyField(related_name='intake_schedule', to='medications.intaketime')),
            ],
        ),
    ]
