# Generated by Django 5.0.6 on 2024-06-14 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeschedule',
            name='medication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medication'),
            preserve_default=False,
        ),
    ]
