# Generated by Django 5.0.6 on 2024-06-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_intaketime_intakeschedule'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.intakeschedule')),
                ('intake_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.intaketime')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], max_length=10)),
                ('type', models.CharField(default='reminder', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.intaketime')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
