# Generated by Django 5.0.6 on 2024-06-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_intakeschedule_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intaketime',
            name='schedule',
        ),
        migrations.AddField(
            model_name='intakeschedule',
            name='times',
            field=models.ManyToManyField(related_name='times', to='medications.intaketime'),
        ),
        migrations.AlterField(
            model_name='intakeschedule',
            name='days',
            field=models.ManyToManyField(related_name='days', to='medications.day'),
        ),
    ]
