# Generated by Django 5.0.6 on 2024-06-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_remove_intaketime_schedule_intakeschedule_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dosage_strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
