# Generated by Django 5.0.6 on 2024-06-14 22:45

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_medication_dosage_strength'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='dosage_strength',
            new_name='strength',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='dosage_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='dosage_unit',
            new_name='unit',
        ),
    ]
